---
- name: Deploy Scientific Calculator
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    container_name: calculator-app
    image_name: yashonidhithakur/scientific-calculator:latest

  tasks:
    - name: Stopping existing container if there is
      shell: /usr/local/bin/docker stop {{ container_name }}
      ignore_errors: yes

    - name: Removing existing container if there is
      shell: /usr/local/bin/docker rm {{ container_name }}
      ignore_errors: yes

    - name: Pulling the latest Docker image
      shell: /usr/local/bin/docker pull {{ image_name }}

    - name: Running the new container in dit mode
      shell: /usr/local/bin/docker run -dit --name {{ container_name }} {{ image_name }}